-- ========================================================================
-- SETUP DE INFRAESTRUTURA - DNA ENGINE
-- Objetivo: Criar as tabelas necessárias para o funcionamento do App.
-- Nota: As antigas Stored Procedures foram removidas, pois o 
-- motor de processamento agora é 100% feito em Python (Single-Pass).
-- ========================================================================

-- 1. Dicionário de Regras Simples (Motor Fase 1)
CREATE OR REPLACE TABLE NOME_DO_BANCO.SCHEMA_SILVER.TB_DICIONARIO_REGRAS (
    CATEGORIA VARCHAR(100) PRIMARY KEY,
    PADRAO_REGEX VARCHAR(500),
    TIPO_REGRA VARCHAR(50),
    PERIODICIDADE VARCHAR(50),
    LIMIAR_VOLUME INTEGER DEFAULT 1,
    COLUNA_ALVO VARCHAR(500),
    MES_INICIO FLOAT DEFAULT 0,
    MESES_RETROATIVOS FLOAT DEFAULT 12,
    SEXO_ALVO VARCHAR(10) DEFAULT 'Ambos',
    IDADE_MIN FLOAT DEFAULT 0,
    IDADE_MAX FLOAT DEFAULT 200,
    DESCRICAO VARCHAR(1000),
    NARRATIVA_CLINICA VARCHAR(1000),
    CONTEXTO_TECNICO VARCHAR(100),
    DT_CRIACAO TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DT_ATUALIZACAO TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 2. Dicionário de Regras Compostas (Motor Fase 2)
CREATE OR REPLACE TABLE NOME_DO_BANCO.SCHEMA_SILVER.TB_DICIONARIO_COMPOSTO (
    CATEGORIA_COMPOSTA VARCHAR(100) PRIMARY KEY,
    REGRAS_OBRIGATORIAS VARCHAR(500),
    REGRAS_ALTERNATIVAS VARCHAR(500),
    REGRAS_EXCLUSAO VARCHAR(500),
    JANELA_COOCORRENCIA_DIAS INTEGER DEFAULT 30,
    EXIGE_ORDEM_CRONOLOGICA INTEGER DEFAULT 0,
    MES_INICIO FLOAT DEFAULT 0,
    MESES_RETROATIVOS FLOAT DEFAULT 12,
    SEXO_ALVO VARCHAR(10) DEFAULT 'Ambos',
    IDADE_MIN FLOAT DEFAULT 0,
    IDADE_MAX FLOAT DEFAULT 200,
    CONTEXTO_TECNICO VARCHAR(100),
    NARRATIVA_CLINICA VARCHAR(1000),
    FL_ATIVO INTEGER DEFAULT 1,
    DT_CRIACAO TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DT_ATUALIZACAO TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 3. Criação da Tabela DNA Base
-- Nota: O Motor Python criará as colunas FL_ automaticamente via ALTER TABLE.
CREATE OR REPLACE TABLE NOME_DO_BANCO.SCHEMA_GOLD.TB_DNA (
    ID_PESSOA VARCHAR,
    DT_NASCIMENTO DATE,
    IDADE INTEGER
);

-- 4. Carga Inicial da Tabela DNA
-- Adapte a origem (FROM) para a sua tabela de Dimensão de Usuários correta.
INSERT INTO NOME_DO_BANCO.SCHEMA_GOLD.TB_DNA (ID_PESSOA, DT_NASCIMENTO, IDADE)
SELECT 
    ID_PESSOA, 
    DT_NASCIMENTO, 
    IDADE 
FROM NOME_DO_BANCO.SCHEMA_SILVER.TB_DIM_USUARIO;
